name: Idp App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEPLOYMENT_PATH: "/opt/idp-monolith"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy via SSH action
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: DEPLOYMENT_PATH
          script: |
            cd $(echo $DEPLOYMENT_PATH)
            git pull
            cp .env.example .env
            # build containers
            make build
            # start containers
            make up
